# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire', models.DateField(blank=True, null=True, verbose_name='date of expire')),
            ],
            options={
                'verbose_name': 'script access',
                'verbose_name_plural': 'script accesses',
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip address')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='date of expire')),
            ],
            options={
                'verbose_name': 'ban',
                'verbose_name_plural': 'bans',
            },
        ),
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('shard', models.CharField(max_length=120, verbose_name='shard')),
                ('char_id', models.CharField(max_length=6, verbose_name='char id')),
                ('public_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='public key')),
            ],
            options={
                'verbose_name': 'char',
                'verbose_name_plural': 'chars',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='name')),
                ('hash', models.CharField(blank=True, editable=False, max_length=12, null=True, verbose_name='hash')),
                ('script', models.FileField(upload_to=b'scripts', verbose_name='script')),
            ],
            options={
                'verbose_name': 'script',
                'verbose_name_plural': 'scripts',
            },
        ),
        migrations.AddField(
            model_name='access',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Char', verbose_name='char'),
        ),
        migrations.AddField(
            model_name='access',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Script', verbose_name='script'),
        ),
        migrations.AlterUniqueTogether(
            name='access',
            unique_together=set([('char', 'script')]),
        ),
    ]
