# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='client',
            field=models.FileField(blank=True, null=True, upload_to='clients', verbose_name='client'),
        ),
    ]
